org: byvsp
service: estoquepro

provider:
    name: aws
    region: us-east-1
    runtime: nodejs22.x
    architecture: arm64

packge:
    individually: true

build:
    esbuild:
        minify: true
        sourcemap: false
